server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5433/search_engine
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    org.springframework: ERROR
    searchengine: INFO


indexing-settings:
  sites:
    - url: https://skillbox.ru/
      name: Skillbox
    - url: http://radiomv.ru/
      name: Radiomv
    - url: http://www.playback.ru/
      name: Playback


connection-settings:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
  referer: https://www.google.com